# Generated by Django 5.0.2 on 2024-03-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pcodigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('precioiva', models.IntegerField()),
                ('fechain', models.CharField(max_length=100)),
                ('cantidad', models.CharField(max_length=100)),
                ('fechavenci', models.CharField(max_length=100)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.categorias')),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preciov', models.IntegerField()),
                ('cantidadv', models.IntegerField()),
                ('fechav', models.CharField(max_length=10)),
                ('metodov', models.CharField(max_length=20)),
                ('productoin', models.CharField(max_length=100)),
                ('productoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.productos')),
            ],
        ),
    ]
